import { MODEL_EXPERIENCE_DOCUMENT } from "/scripts/model-experience-data.js?v=5";
import { SEARCH_EXPERIENCE_DOCUMENT } from "/scripts/search-experience-data.js?v=6";
import { BILIBILI_DOCUMENT } from "/scripts/bilibili-experience-data.js?v=1";

export const OVERVIEW_IMAGE = "/assets/rooms/home-overview-decorated.png?v=2";
export const OVERVIEW_SIZE = { width: 1487, height: 1058 };
export const SHOW_HOTSPOTS = false;

export const PORTFOLIO = {
  authorName: "杨昕乔",
  indexLabel: "Project Index",
  indexDescription: "Work grouped by spatial categories",
  edition: "Portfolio / 2026",
};

// Hotspots use the overview image's 1487 x 1058 coordinate space so they stay
// aligned at every rendered size. The same paths also drive the focus clipPath.
export const ROOMS = [
  {
    id: "garden",
    number: "01",
    title: "Garden",
    path: "/rooms/garden",
    image: "/assets/rooms/garden-cutout.png",
    directoryImage: "/assets/rooms/home-directory-flower.png",
    alt: "Isometric garden terrace with plants, wicker seating, and a bicycle",
    description: "A category for experimental image-making and visual studies.",
    projects: [
      { id: "project-01", title: "Project placeholder 01", type: "Visual study", year: "2026" },
      { id: "project-02", title: "Project placeholder 02", type: "Image making", year: "2025" },
    ],
    documents: [
      {
        id: "garden-finance-video",
        title: "《会理财更会生活》",
        columnLabel: "作品视频",
        format: "MP4",
        contentType: "video",
        file: "/assets/works/garden-finance-video/finance-life.mp4",
      },
      {
        id: "garden-finance-introduction",
        title: "《会理财更会生活》作品介绍",
        columnLabel: "作品介绍",
        contentType: "text",
        textSections: [
          {
            heading: "作品信息",
            plainItems: true,
            items: [
              { title: "作品名称", text: "《会理财更会生活》" },
              { title: "类别", text: "短视频" },
              { title: "广告品牌", text: "招商银行“朝朝宝”" },
            ],
          },
          {
            heading: "创意思想",
            paragraphs: [
              "本视频广告从低风险高收益的产品优势切入，结合大学生等受众群体与年轻化的品牌特性，以年轻有活力的大学生为视频主角，直击年轻受众热爱享受生活、热衷搞钱的营销痛点，吸引眼球，让“朝朝宝”成为让消费者“一下就爱上”的 app。",
              "视频决定采用分屏方式，以此通过对比的手法展示：具有基本相同生活背景的两人，因为是否使用朝朝宝，而导致截然不同的生活，以此凸显朝朝宝高收益低风险的热门优势，以及零钱理财、随存随理、随取随花的便捷性。使用朝朝宝的便利与优势拉近品牌与大学生之间的距离，选择朝朝宝不只是短期的资金投资，更是长期的人生投资，用零碎时间理零碎的钱，空出的时间就用来理理自己的生活！",
            ],
          },
        ],
      },
      {
        id: "garden-ai-knowledge-platform",
        title: "AI 知识加工台",
        format: "Product Experience",
        contentType: "memory",
        memory: {
          index: "01 / 03",
          title: "AI 知识加工台",
          tagline: "让企业知识从“存下来”变成“用起来”",
          meta: "2024.07 · 产品运营",
          heroTagline: "让企业知识从“存下来”变成真正可用的工作成果",
          productIntro: "AI 知识加工台面向企业办公场景，帮助用户把分散资料转化为可以继续使用的工作成果。",
          product: "AI 知识加工台面向企业办公场景，用户可以导入周报、会议纪要、知识库文档和本地文件，通过 AI 完成内容理解、信息提炼，并生成 PPT、信息图、总结等可以继续使用的工作成果。",
          role: "我负责围绕重点功能迭代开展运营。从真实工作困境中提炼内容切口，将抽象的 AI 能力转化为用户容易理解的办公场景，并通过功能上新、场景教育和使用内容，推动用户从“知道产品”走向创建、使用和持续提问。",
          features: [
            { number: "01", title: "PPT 生成", iteration: "基于用户已有资料生成结构完整的演示文稿，减少从整理材料到搭建汇报页面的重复工作。", operation: "从“临时接到汇报，材料很多却来不及做 PPT”的真实困境切入，通过上传资料到生成初稿的过程，让用户直观看到功能价值。", expression: "材料都在手里，PPT 怎么还是做不完？" },
            { number: "02", title: "信息图生成", iteration: "将长文档中的重点内容提炼为结构清晰的信息图，帮助用户更快阅读和传播复杂信息。", operation: "从“内容写得很完整，但没人愿意看完”切入，用长文档与一页信息图的前后对比，呈现信息压缩和视觉表达的价值。", expression: "一整份材料，能不能用一张图讲清楚？" },
            { number: "03", title: "周报生成", iteration: "基于已有工作资料归纳阶段进展，辅助用户快速生成结构化周报内容。", operation: "抓住每周重复回忆、整理和组织表达的痛点，强调 AI 是从已有材料中提取重点，而不是替用户虚构工作。", expression: "周报最难的，可能不是写，而是想起这周做了什么。" },
            { number: "04", title: "知识库问答", iteration: "支持用户围绕知识库内容持续提问、定位信息和提炼结论，让沉淀的资料可以被反复调用。", operation: "从“文档存了很多，真正要用时却找不到”切入，展示用户如何从资料检索进一步进入知识复用。", expression: "知识库里什么都有，为什么每次还要重新找？" },
          ],
          kpis: [
            { value: "512", label: "创建笔记本 UV · 08.10—08.16" },
            { value: "1,246", label: "创建笔记本 PV · 08.10—08.16" },
            { value: "619", label: "实际使用 UV · 08.10—08.16" },
            { value: "2,425", label: "实际使用 PV · 08.10—08.16" },
          ],
          monthly: [
            { label: "创建笔记本 UV", old: "451", new: "512", oldPercent: 88, newPercent: 100, delta: "+13.5%" },
            { label: "创建笔记本 PV", old: "1,054", new: "1,246", oldPercent: 85, newPercent: 100, delta: "+18.2%" },
            { label: "实际使用 UV", old: "397", new: "619", oldPercent: 64, newPercent: 100, delta: "+55.9%" },
            { label: "实际使用 PV", old: "2,022", new: "2,425", oldPercent: 83, newPercent: 100, delta: "+19.9%" },
          ],
          path: [{ label: "创建", count: "512 UV" }, { label: "使用", count: "619 UV" }, { label: "提问", count: "738 UV" }],
          insight: "PPT、信息图、周报和知识库四类任务贡献约 72% 的流量，其中 PPT 约 33%，信息图约 19%，周报约 11%，知识库约 9%。运营重点不只是让用户知道产品，而是持续推动用户进入创建、使用和提问这条核心链路。",
          contentArchive: [
            { number: "01", title: "PPT 生成功能上新", function: "PPT 生成", type: "功能上新 / 场景教育", theme: "材料都在手里，PPT 怎么还是做不完？", description: "从临时汇报、材料堆积和时间不足的工作困境切入，讲清楚用户如何把已有资料交给 AI，快速获得一份可以继续修改的汇报初稿。" },
            { number: "02", title: "信息图场景教育", function: "信息图生成", type: "场景教育 / 使用引导", theme: "一整份材料，能不能用一张图讲清楚？", description: "用“一整份长文档”和“一张信息图”的差异，说明 AI 如何帮助用户提炼重点、压缩信息，让复杂内容更容易被阅读和传播。" },
            { number: "03", title: "周报生成使用内容", function: "周报生成", type: "使用教程 / 场景内容", theme: "周报最难的，可能不是写，而是想起这周做了什么。", description: "围绕“每周都要重新回忆和整理工作”的痛点展开，说明 AI 可以从已有材料中找到工作进展，帮助用户更快组织成周报，而不是凭空生成内容。" },
            { number: "04", title: "知识库问答内容", function: "知识库问答", type: "功能介绍 / 深度使用", theme: "知识库里什么都有，为什么每次还要重新找？", description: "从“资料已经沉淀，但真正需要时找不到”切入，展示用户如何通过连续提问定位信息、提炼结论，再把知识库内容转化为可继续使用的工作成果。" },
          ],
          paragraphs: [
            { key: "definition", lead: "面向企业办公场景的 AI 知识处理产品", body: "AI 知识加工台是一款面向企业办公场景的 AI 知识处理产品。它将分散在周报、会议纪要、知识库文档和本地文件中的信息集中到同一个笔记本，通过 AI 完成资料理解、内容问答与信息提炼，并进一步生成 PPT、信息图、工作总结、会议纪要和播客等成果。产品的核心价值，是让企业知识不只被“存下来”，还能够被快速理解、重新加工，并直接进入汇报、复盘、会议等真实工作流程。" },
            { key: "iteration", lead: "围绕「知识输入—AI 理解—内容加工—成果交付」的链路", body: "围绕“知识输入—AI 理解—内容加工—成果交付”的逻辑，我参与了经典 PPT、信息图、工作总结、可信问答、播客及移动端文件导入等能力迭代。随着输出形态不断丰富，产品也从单一的资料问答工具，逐步拓展到总结复盘、内容创作和汇报交付等场景，帮助用户用更低的操作成本完成从原始资料到工作成果的转换。" },
            { key: "operation", lead: "把抽象的 AI 能力转化为可理解、可尝试的使用场景", body: "具体推进中，我从用户痛点、具体使用场景出发，将相对抽象的 AI 能力转化为更容易理解和尝试的使用场景：围绕季度复盘、会议总结、PPT 制作、长文档阅读等需求提炼功能卖点，配合重点能力上线完成内容策划、案例包装和使用引导；同时通过体验活动、作品分享和评论互动，推动用户完成创建笔记本、导入资料、发起任务和持续提问等关键行为。结合知识库、数字员工入口和移动端等渠道进行分发，并持续分析用户规模、任务结构、使用深度和留存表现，调整重点场景与内容策略。" },
            { key: "result", lead: "BI 数据反馈", body: "根据 BI 数据，在迭代和运营推进期间，7月周均创建笔记本 UV 较6月增长 51.6%，使用 UV 增长 35.6%，提问 UV 增长 25.8%，发起任务 UV 增长 33.6%。截至统计周期末，产品累计沉淀 7,228 名创建用户，其中 5,574 名用户进入实际使用，创建至使用转化率达到 77.1%；累计产生约 4.1万次任务和 1.37万次提问，提问用户人均发起约 4.6 次问答。从任务结构看，PPT、信息图、周报和知识库任务贡献了约 72% 的任务量，其中 PPT 以 32.8% 的占比成为最突出的核心场景。这说明用户不仅开始接触产品，也逐步将其用于内容生产与知识加工等真实工作任务。运营重点由“让用户知道产品”，进一步推进到帮助用户建立使用习惯、进入核心链路并形成稳定的场景认知。" },
          ],
          highlights: ["51.6%", "35.6%", "25.8%", "33.6%", "7,228", "5,574", "77.1%", "4.1万", "1.37万", "4.6", "72%", "32.8%"],
          flow: {
            left: { label: "知识输入", sub: "周报 · 会议纪要 · 知识库 · 本地文件" },
            middle: { label: "AI 理解", sub: "资料理解 · 内容问答 · 信息提炼" },
            right: { label: "成果交付", sub: "PPT · 信息图 · 总结 · 播客" },
          },
          taskDistribution: [
            { label: "PPT", percent: 32.8, highlight: true },
            { label: "信息图", percent: 15.4 },
            { label: "周报", percent: 13.9 },
            { label: "知识库", percent: 10.3 },
            { label: "其他", percent: 27.6 },
          ],
          taskMix: [
            { label: "PPT演示文稿", uv: "4,309", pv: "28,570", share: "33%" },
            { label: "信息图", uv: "2,942", pv: "16,542", share: "19%" },
            { label: "周报", uv: "3,435", pv: "8,884", share: "11%" },
            { label: "知识库", uv: "1,632", pv: "7,464", share: "9%" },
          ],
          metrics: [
            { value: "+51.6%", numeric: 51.6, prefix: "+", suffix: "%", decimals: 1, label: "创建笔记本 UV 增长" },
            { value: "+35.6%", numeric: 35.6, prefix: "+", suffix: "%", decimals: 1, label: "使用 UV 增长" },
            { value: "7,228", numeric: 7228, label: "累计创建用户" },
            { value: "4.1万+", numeric: 4.1, suffix: "万+", decimals: 1, label: "累计任务" },
          ],
          funnel: [
            { stage: "创建", count: "7,228", rate: "100%" },
            { stage: "使用", count: "5,574", rate: "77.1%" },
            { stage: "提问", count: "2,951", rate: "40.8%" },
          ],
          bars: [
            { label: "PPT", percent: 32.8, delta: "+5.2pp", highlight: true },
            { label: "信息图", percent: 15.4, delta: "+1.8pp" },
            { label: "周报", percent: 13.9, delta: "+0.6pp" },
            { label: "知识库", percent: 10.3, delta: "-0.4pp" },
            { label: "其他", percent: 27.6, delta: "+3.1pp" },
          ],
        },
      },
      MODEL_EXPERIENCE_DOCUMENT,
      SEARCH_EXPERIENCE_DOCUMENT,
      BILIBILI_DOCUMENT,
    ],
    objectHotspots: [
      {
        id: "garden-cushion-01",
        number: "02",
        label: "AI 知识加工台",
        directoryImage: "/assets/rooms/objects/garden-cushion-01.png",
        ariaLabel: "打开 01 号记忆：AI 知识加工台",
        documentId: "garden-ai-knowledge-platform",
        path: "M 1174 883 C 1192 866 1228 864 1252 875 L 1314 892 L 1329 923 L 1325 979 L 1301 1011 L 1238 1014 L 1187 1002 L 1168 972 L 1166 919 Z",
        glowImage: { file: "/assets/rooms/objects/garden-cushion-01.png", x: 1165, y: 865, width: 170, height: 155 },
      },
      {
        id: "garden-cushion-02",
        number: "03",
        label: "模型体验台",
        directoryImage: "/assets/rooms/objects/garden-cushion-02.png",
        ariaLabel: "打开 02 号经历：模型体验台",
        documentId: "garden-model-experience",
        path: "M 1246 944 C 1267 929 1304 929 1333 941 L 1388 959 L 1404 990 L 1399 1040 L 1369 1074 L 1309 1077 L 1260 1060 L 1239 1031 L 1238 979 Z",
        glowImage: { file: "/assets/rooms/objects/garden-cushion-02.png", x: 1234, y: 923, width: 178, height: 166 },
      },
      {
        id: "garden-cushion-03",
        number: "04",
        label: "AI 搜索",
        directoryImage: "/assets/rooms/objects/garden-cushion-03.png",
        ariaLabel: "打开 03 号经历：AI 搜索",
        documentId: "garden-ai-search",
        path: "M 1535 1028 L 1502 1072 L 1477 1113 L 1476 1127 L 1498 1178 L 1499 1178 L 1525 1152 L 1567 1130 L 1574 1119 L 1574 1107 L 1568 1088 L 1554 1066 L 1535 1028 Z",
        glowPath: "M 1535 1028 L 1502 1072 L 1477 1113 L 1476 1127 L 1498 1178 L 1499 1178 L 1525 1152 L 1567 1130 L 1574 1119 L 1574 1107 L 1568 1088 L 1554 1066 L 1535 1028 Z",
      },
      {
        id: "garden-bike",
        number: "01",
        label: "《会理财更会生活》",
        directoryImage: "/assets/rooms/objects/garden-bike.png",
        documentIds: ["garden-finance-video", "garden-finance-introduction"],
        path: "M 520 1370 C 522 1328 568 1312 625 1320 L 682 1368 L 817 1360 L 859 1395 L 876 1464 L 900 1533 L 888 1625 L 848 1688 L 789 1695 L 744 1650 L 705 1574 L 650 1542 L 604 1518 L 548 1494 L 520 1438 Z",
        glowImage: {
          file: "/assets/rooms/objects/garden-bike.png",
          x: 520,
          y: 1315,
          width: 380,
          height: 380,
        },
      },
      {
        id: "garden-book",
        number: "05",
        label: "B站 UP 主自述档案",
        directoryImage: "/assets/rooms/objects/garden-book.png",
        ariaLabel: "打开 B站 UP 主自述档案",
        documentId: "garden-bilibili-profile",
        path: "M 1080 1177 L 1221 1245 L 1219 1263 L 1103 1341 L 973 1277 L 972 1258 Z",
        glowMask: {
          file: "/assets/rooms/objects/garden-red-book-mask.png?v=1",
        },
      },
    ],
    hotspotPath: "M478 360 L512 391 L744 498 L540 617 L540 789 L309 613 L309 596 L337 580 L337 523 L360 510 L371 474 L411 466 L430 438 L461 421 Z",
    hotspotCenter: { x: 480, y: 585 },
    transition: {
      sourceFinal: { x: 3.2, y: -1.5, scale: 1.17, blur: 6 },
      detailInitial: { x: -22.5, y: 1.5, scale: 0.58, blur: 6 },
    },
  },
  {
    id: "kitchen",
    number: "02",
    title: "Kitchen",
    path: "/rooms/kitchen",
    image: "/assets/rooms/kitchen-cutout.png",
    directoryImage: "/assets/rooms/home-directory-tableware.png",
    alt: "Isometric kitchen and dining room with timber cabinetry and a dining table",
    description: "A category for systems, identity, and structured design practice.",
    projects: [
      { id: "project-01", title: "Project placeholder 01", type: "Design system", year: "2026" },
      { id: "project-02", title: "Project placeholder 02", type: "Visual identity", year: "2025" },
    ],
    documents: [
      {
        id: "heartprint-marketing",
        title: "心相印营销策划",
        columnLabel: "策划案",
        format: "PDF",
        pages: 33,
        file: "/assets/works/kitchen-heartprint-campaign/heartprint-marketing.pdf",
        renderedPages: {
          basePath: "/assets/works/kitchen-heartprint-campaign/pages",
          extension: "jpg",
          width: 1560,
          height: 1080,
        },
      },
      {
        id: "heartprint-introduction",
        title: "心相印「这张纸巾记得」作品介绍",
        columnLabel: "作品介绍",
        contentType: "text",
        textSections: [
          {
            heading: "作品概述",
            paragraphs: [
              "参赛学院奖，针对恒安心相印云感柔肤系列纸巾打造的完整整合情感营销全案，以友情为核心情感切口，提炼主传播主题「这张纸巾记得」。方案跳出生活用纸行业同质化功能宣传的内卷，把纸巾从单纯清洁日用品，转化为承载青春回忆、见证挚友悲欢的情感载体，依托内容营销 5A 模型搭建四阶段传播链路，联动线上线下明星合作、UGC 话题、线下快闪与公益长线运营，为品牌构建差异化情感记忆点，最终实现年轻群体情感共鸣、品牌好感度与产品转化同步提升。",
            ],
          },
          {
            heading: "核心亮点",
            paragraphs: [
              "区别于常规日用品只做功能卖点的策划思路，跳出产品本身，抓住“纸巾见证友情”这一极易共情的微小生活场景，把快消品赋予浓厚人文情感；同时完整打通“预热 - 爆火 - 体验 - 长效”全周期营销链路，兼顾流量热度、用户参与、产品带货与品牌社会责任，策略完整、物料体系丰富，兼具创意感染力与商业落地可行性。",
            ],
          },
          {
            heading: "选题策划思路",
            paragraphs: [
              "前期梳理纸巾行业市场现状时我发现，维达、洁柔、清风等竞品全部聚焦柔韧、吸水、平价等物理卖点，几乎没有品牌深耕大众日常用纸背后的情绪场景；同时心相印自身“用心关爱身边每一个人”的品牌理念传播浅层，缺少能让年轻人记住的专属故事与情感符号。",
              "结合 Z 世代大学生、年轻上班族的用户洞察：当下年轻人社交压力大，极度渴求真挚友情带来的情绪慰藉，纸巾又是友情场景里高频出现的道具 - 难过时递纸巾、大笑擦眼泪、分享小纸条，无数细碎温暖瞬间都和纸巾绑定。基于这个生活化的共情切入点，我敲定以“友情见证者”为品牌新定位，确立“这张纸巾记得”核心主题，把产品柔软亲肤的使用感受，和朋友之间温柔治愈的陪伴感做绑定，让产品功能与情感价值双向契合，打造区别于竞品的独家品牌叙事。",
            ],
          },
          {
            heading: "完整落地工作",
            subsections: [
              {
                heading: "一、市场与用户调研（行业 / 竞品 / 消费者三维分析）",
                items: [
                  { title: "行业宏观分析", text: "完成 PEST 政策、经济、社会、技术四维拆解，梳理低碳环保政策、消费升级、短视频渠道崛起等行业机遇与挑战，明确生活用纸高端化、情感化是未来营销核心趋势。" },
                  { title: "品牌 SWOT 诊断", text: "梳理心相印自身品牌优势、传播短板、市场机会与同质化竞争威胁，精准定位品牌核心痛点 - 缺少深入人心的情感记忆，无法和年轻用户建立深度情感联结。" },
                  { title: "竞品对标分析", text: "横向拆解维达、洁柔、清风三大头部品牌传播逻辑，总结行业共性问题：重功能、轻故事，无专属情感标签，为本方案差异化策略提供依据。" },
                  { title: "目标用户深度调研", text: "设计 25 题定量消费者问卷，覆盖 18-35 岁 Z 世代群体，从消费习惯、社交偏好、情感需求、广告接受形式多维度收集数据，提炼三类典型用户画像（大学生、甜品师、职场程序员），确认年轻人愿意为品牌情绪价值买单、热衷短视频 UGC、对综艺好友向内容好感度高，以此确定后续明星合作、短视频、线下活动的落地方向。" },
                ],
              },
              {
                heading: "二、整体策略规划",
                paragraphs: ["以内容营销 5A 模型为底层逻辑，划分四大递进营销阶段，完整搭建传播节奏："],
                items: [
                  { title: "心相遇・曝光预热（Aware）", text: "国际友谊日上线温情 TVC，用高中、大学、异地多年好友的成长故事，铺垫“纸巾见证友情”的核心概念，完成品牌情感基调预埋。" },
                  { title: "心相识・爆点破圈（Attract）", text: "联动高国民度友情向综艺团体十个勤天，定制品牌主题曲《你是我的心朋友》，同步上线粉丝混剪短视频、一二线城市地铁大屏户外投放，借助明星流量快速破圈，制造全网话题热度。" },
                  { title: "心相知・体验转化（Ask & Act）", text: "抖音双话题挑战赛引导用户自主分享友情旧照、暖心瞬间，产出海量 UGC 内容；落地商场线下快闪店，设置好友默契互动游戏、产品试用、故事分享墙，打通线上流量到线下体验、线下打卡反哺线上传播的闭环，同步推出联名款纸巾周边，带动产品销售转化。" },
                  { title: "心相伴・长效维护（Advocate）", text: "联动温情生活类 KOL 打造公益短片，发起 #交个“心”朋友# 山区书信公益活动，把短期营销热度转化为长期品牌口碑，通过公益叙事强化品牌人文温度，沉淀忠实用户。" },
                ],
                paragraphsAfter: ["同时完整测算全案 377 万预算，拆分视频制作、明星合作、线上投流、线下场地、公益物料等细分开支，制作分阶段媒介排期表，精准规划 7-9 月全渠道投放节奏，兼顾传播效果与成本可控性。"],
              },
              {
                heading: "三、全套视觉创意设计（品牌传播物料产出）",
                paragraphs: ["围绕“温柔、青春、治愈”视觉调性，完成整套营销视觉物料设计，统一品牌视觉语言："],
                items: [
                  { title: "主视觉物料", text: "TVC 广告封面、品牌主题曲宣传海报、地铁大屏户外海报，融合山野、校园、好友同框等生活化场景，搭配手写体温情文案，呼应“一起哭过笑过的日子”主题。" },
                  { title: "线下空间视觉", text: "购物中心快闪店爱心主装置、活动打卡墙、人流区导视展板，统一心相印品牌绿色主色调，融入云感柔肤产品元素，打造沉浸式友情氛围打卡场景。" },
                  { title: "产品衍生视觉", text: "十个勤天联名纸巾包装、公益定制款纸巾、书信信封 / 信纸周边，把主题标语、友情插画融入产品包装，实现产品本身成为传播载体。" },
                  { title: "社交平台配图", text: "微博、抖音活动宣发长图、公益公关海报，适配短视频、信息流、朋友圈多渠道尺寸，兼顾线上传播轻量化、氛围感。" },
                ],
              },
            ],
          },
          {
            heading: "参与复盘",
            paragraphs: ["整套方案从 0 到 1，完整覆盖市场调研、用户洞察、策略建模、整合传播策划、预算排期、视觉创意统筹全流程工作："],
            items: [
              { title: "系统化市场分析", text: "熟练运用 PEST、SWOT、竞品对标、问卷调研等专业工具，能精准挖掘行业空白与用户真实情绪需求，不局限于产品功能，从情感维度打造差异化营销切口。" },
              { title: "内容营销 5A 模型", text: "可搭建线上线下联动、短期爆点 + 长期口碑并行的整合传播链路，兼顾流量破圈、用户互动、产品转化、品牌长效价值多重营销目标。" },
              { title: "全品类视觉统筹", text: "能根据传播渠道、活动阶段匹配对应视觉风格，实现广告、线下场景、产品周边视觉统一，让创意主题落地可感知。" },
              { title: "商业策划思维", text: "可独立完成项目预算拆分、媒介投放排期规划，平衡创意效果与落地成本，方案兼顾比赛创意性与真实市场可执行性。" },
              { title: "年轻群体传播洞察", text: "擅长把握 Z 世代年轻群体传播逻辑，融合明星跨界、短视频 UGC、线下快闪、公益营销等当下主流营销玩法，懂得用生活化、共情化故事替代硬广推销，贴合当代年轻人接收广告的偏好。" },
            ],
          },
        ],
        file: "/assets/works/kitchen-heartprint-introduction/heartprint-introduction.pdf",
      },
      {
        id: "popmart-marketing",
        title: "泡泡玛特「酷导演的剧本 —— 泡泡梦工厂」整合营销策划",
        columnLabel: "策划案",
        format: "PDF",
        pages: 30,
        file: "/assets/works/kitchen-popmart-campaign/popmart-marketing.pdf",
        renderedPages: {
          basePath: "/assets/works/kitchen-popmart-campaign/pages",
          extension: "jpg",
          width: 1560,
          height: 878,
        },
      },
      {
        id: "popmart-introduction",
        title: "泡泡玛特「酷导演的剧本 —— 泡泡梦工厂」作品介绍",
        columnLabel: "作品介绍",
        contentType: "text",
        textSections: [
          {
            heading: "作品概述",
            paragraphs: [
              "本作品是面向泡泡玛特 SKULLPANDA 人生如戏系列打造的完整长线情感文化营销方案，主打潮玩 × 戏剧跨界融合，参赛学院奖。洞察到泡泡玛特现有 IP 仅有形象输出、缺少完整世界观与叙事体系、品牌精神表达单薄的核心痛点后，我选取 SKULLPANDA 隐藏款「酷导演」作为核心主角，原创完整“SP 奇想穿越造梦”故事主线，搭建「泡泡梦工厂」全新品牌概念，把品牌定位升级为“守护普通人想象力、为大众造梦的精神乐园”。整体传播按照入梦 - 造梦 - 护梦三阶段分层落地，联动综艺、乌镇戏剧节、线下沉浸式剧场、线上互动玩法、青年戏剧公益等多元形式，补齐泡泡玛特文化短板，打破潮玩小众圈层壁垒，为 IP 赋予长效故事生命力，同时强化品牌治愈、包容、鼓励自我表达的情绪价值。",
            ],
          },
          {
            heading: "核心亮点",
            items: [
              { title: "填补品牌核心空白", text: "原创完整 SKULLPANDA 酷导演故事与品牌世界观，解决泡泡玛特 IP“只有形象没有灵魂”的行业通病，赋予产品长久内容生命力。" },
              { title: "差异化赛道突围", text: "跳出潮玩常规促销、新品宣发模式，绑定戏剧艺术做跨界文化营销，把盲盒从消费品升级为情绪、幻想的文化载体，区分所有竞品策划思路。" },
              { title: "线上线下完整闭环", text: "从综艺预热、线上 UGC 共创，到乌镇戏剧节线下落地、全国沉浸式巡演，最后以公益项目长效维稳，传播链路完整，兼具短期话题热度与长期品牌沉淀。" },
              { title: "兼顾破圈与深度共情", text: "一方面用综艺、趣味 H5 吸引普通路人破除潮玩小众标签，另一方面用梦境故事、戏剧体验打动核心玩家，兼顾大众传播与粉丝深度情感联结。" },
            ],
          },
          {
            heading: "选题策划思路",
            paragraphs: [
              "在前期行业与品牌调研时我发现泡泡玛特存在明显发展短板：品牌坐拥海量原创 IP、渠道完善，但绝大多数 IP 只停留在外观形象层面，没有统一世界观、完整人物故事与价值内核，消费者仅为颜值买单，很难产生深度情感绑定；同时大众对潮玩仍存在“只是摆件、没有内涵”的刻板印象，品牌同质化竞争严重，单纯靠新品盲盒很难长期留住用户。",
              "结合 Z 世代核心需求：当代年轻人压力大，内心拥有大量幻想、未实现的梦想，渴望一个能释放想象力、投射自我的精神载体；而戏剧恰好是“造梦、演绎不同人生、表达内心”的艺术载体，和 SKULLPANDA“穿梭不同时空、扮演多样自我”原生设定高度契合。",
              "因此我选定 SP 人生如戏系列酷导演为叙事核心，原创完整成长穿越故事：SP 从小热爱幻想、偶然闯入泡泡异世界，经历多重人生后立志成为造梦导演，由此引出「泡泡梦工厂」主题。以戏剧为差异化赛道，跳出潮玩常规带货营销，用完整故事 + 艺术跨界填充品牌文化空白，让盲盒不止是收藏品，更是承载每个人梦境与自我表达的媒介。",
            ],
          },
          {
            heading: "完整落地工作内容",
            subsections: [
              {
                heading: "一、市场调研",
                items: [
                  { title: "PEST 行业宏观研判", text: "梳理潮玩行业政策规范、市场规模增长、Z 世代消费特征、线上数字化渠道四大维度，明确行业走向文化、情感、体验化；同时指出盗版、IP 生命周期短、盲盒监管收紧等行业风险。" },
                  { title: "品牌深度 SWOT 拆解", text: "梳理泡泡玛特全产业链、会员社群优势；深挖 IP 故事缺失、产品实用性弱、大众认知局限等劣势；捕捉本土潮玩崛起、IP 多元化布局市场机会；预判竞品分流、用户审美疲劳等外部威胁，精准锁定本次策划核心解决方向 - 补齐品牌世界观与情感叙事。" },
                  { title: "竞品对标分析", text: "横向对比 52TOYS、IP 小站、Suplay 三大潮玩竞品，总结行业普遍短板：大多只侧重渠道铺货，缺少深度文化内容营销，印证本次“故事 + 戏剧跨界”差异化策略可行性。" },
                  { title: "定量消费者问卷调研", text: "设计 15 题专项问卷，覆盖 18-35 岁学生、白领核心人群，统计用户购盒动机、价格接受度、内容偏好、对 IP 故事的需求程度，提炼“情绪治愈、自我表达、社交收藏”三大核心消费诉求，为 H5 测试、共创征集、线下戏剧等活动提供数据支撑。" },
                ],
              },
              {
                heading: "二、完整故事世界观与策略体系",
                items: [
                  { title: "原创 IP 主线叙事创作", text: "以 SKULLPANDA 酷导演为主角，独立撰写完整人物前传与奇幻穿越故事，构建统一「泡泡梦工厂」世界观，串联“幻想 - 入梦 - 穿越多元人生 - 成为造梦导演”完整剧情，赋予 IP 成长弧光，填补品牌故事空白，所有营销活动全部围绕这条故事线展开，实现内容统一闭环。" },
                  { title: "入梦・圈层破圈预热", text: "联动头部综艺《一年一度喜剧大赛》跨界曝光，上线「测测你的泡泡玛特人格」互动 H5 小游戏，用轻趣味测试降低大众认知门槛，吸引非潮玩受众，完成前期话题铺垫。" },
                  { title: "造梦・内容深度爆发", text: "绑定戏剧核心赛道，落地乌镇戏剧节线下主题展，发起全民梦境故事 UGC 共创，联合青年戏剧人拍摄品牌微电影，线上线下同步输出完整 SP 世界观故事，完成从曝光到情感共鸣转化。" },
                  { title: "护梦・长效价值沉淀", text: "落地全国沉浸式戏剧线下巡演，配套线上互动冒险小游戏，同步发起扶持青年戏剧创作者的公益项目，把短期流量转化为品牌长期文化资产，提升品牌社会好感与用户粘性。" },
                ],
                paragraphsAfter: [
                  "项目预算与媒介排期规划：独立拆分全案 491 万细分预算，覆盖综艺赞助、线下剧场、KOL 投放、微电影制作、公益基金、H5 开发等全部开支；制作分月媒介投放排期表，区分微博 / 抖音 / B 站 / 线下剧场 / 商场大屏多渠道投放节奏，兼顾创意落地效果与成本可控性。",
                ],
              },
              {
                heading: "三、视觉物料创意输出",
                paragraphs: ["围绕“梦幻剧场、温柔造梦”统一视觉调性，完成全链路宣传物料设计："],
                items: [
                  { title: "跨界联名视觉", text: "《一年一度喜剧大赛》联动海报、节目舞台视觉、中插广告画面，融合喜剧元素与 SP 酷导演 IP 形象。" },
                  { title: "戏剧主题主视觉", text: "乌镇戏剧节「泡泡梦工厂」线下展主 KV、场馆导视牌、泡泡装置画面，贴合剧场氛围感。" },
                  { title: "线上互动物料", text: "人格测试 H5 页面、梦境共创话题配图、线上互动游戏场景原画、微博热搜话题长图。" },
                  { title: "线下空间视觉", text: "沉浸式戏剧巡演剧场门头、打卡装置、隐藏剧情提示物料。" },
                  { title: "公益宣传物料", text: "青年造梦公益短片封面、基金会宣传海报，整套视觉贯穿“剧场、泡泡、梦境、SP 酷导演”核心元素，保证全活动视觉语言统一。" },
                ],
              },
            ],
          },
          {
            heading: "个人能力复盘",
            paragraphs: ["整套策划从市场摸底、世界观原创、策略搭建到活动落地、视觉统筹、预算排期全程独立完成，完整覆盖整合营销全链条专业工作："],
            items: [
              { title: "市场洞察与差异化定位能力", text: "能够精准挖掘品牌隐性短板，避开行业同质化带货思路，找到“IP 世界观缺失”核心痛点，锁定戏剧文化细分赛道，打造区别于所有潮玩品牌的独家内容营销路线。" },
              { title: "原创内容叙事能力", text: "独立完成 IP 完整故事线、品牌世界观创作，将单一盲盒 IP 拓展为有成长、有内核、可延伸的完整角色体系，实现所有营销活动与故事主线高度绑定。" },
              { title: "整合传播策略搭建能力", text: "熟练使用分阶段递进传播逻辑，兼顾线上轻量化互动、线下沉浸式艺术体验、长线公益口碑运营，实现破圈引流、用户转化、品牌价值提升三重目标。" },
              { title: "全渠道活动落地规划能力", text: "掌握综艺联名、线下艺术展、UGC 共创、沉浸式演出、H5 小游戏、公益项目等多元营销玩法，能统筹线上社媒、线下实体空间双渠道联动传播。" },
              { title: "商业落地思维", text: "可独立完成项目整体预算拆解、分渠道媒介排期，兼顾创意艺术性与真实市场落地可行性，同时通过公益板块拔高品牌人文价值，提升方案完整度与大赛竞争力。" },
              { title: "年轻化传播把控力", text: "精准把握 Z 世代社交习惯，善用人格测试、故事征集、线下打卡分享等社交裂变玩法，降低潮玩圈层门槛，实现大众群体破圈传播。" },
            ],
          },
        ],
      },
      {
        id: "kitchen-distant-view",
        title: "可远观不可亵玩",
        format: "PDF",
        pages: 1,
        file: "/assets/works/kitchen-distant-view/distant-view.pdf",
        introduction: {
          kicker: "01 / 作品介绍",
          heading: "AI 知识加工台「经典 PPT」功能推广运营",
          paragraphs: [
            "本作品是面向百度内部全体员工产出的产品推广运营内容，发布于公司内部知识库平台，主要触达日常需要频繁制作 PPT、撰写汇报方案的办公人群。整体不只是一篇功能宣传文稿，同步配套设计了站内抽奖互动活动，形成完整的内部推广运营方案。推广对象是百度文库联合共建的 AI 知识加工台，该平台依托文库、学术专业资料库生成可溯源、逻辑完整的专业内容，本次核心推广其全新上线的「经典 PPT」生成功能。",
            "在策划与撰写阶段，我先梳理了内部员工使用各类 AI 生成工具的真实办公痛点：过往 AI 输出多为无法二次修改的图片文件，版式模板千篇一律，页数、内容详略、图表配图都不能自主调整，很难直接投入正式工作。基于这些普遍困扰，我确定了全文叙事逻辑，从临时收到 PPT 修改需求的真实职场场景切入引发受众共鸣，把“AI 生成 PPT 可原生编辑”作为核心传播亮点，文案全程简化专业术语，用贴近日常办公的通俗表述拆解各项功能优势，降低员工理解门槛。",
            "除正文文案外，运营活动还包括设计低门槛站内裂变抽奖机制，设置 17 份激励奖品带动员工自发分享试用；文末嵌入产品操作指南、实战案例文档与社群、对接人反馈渠道，搭建从内容阅读、工具上手到意见收集的完整用户链路。内容上线后传播效果突出，单周站内浏览量位列全厂第一，顺利完成新功能曝光，日均 PV / UV 上涨 1k+。",
          ],
        },
        renderedPages: {
          basePath: "/assets/works/kitchen-distant-view/pages",
          extension: "jpg",
          width: 1660,
          height: 12608,
        },
      },
      {
        id: "kitchen-processing-platform",
        title: "无暇不出——加工台运营稿",
        format: "PDF",
        pages: 1,
        file: "/assets/works/kitchen-processing-platform/kitchen-processing-platform.pdf",
        renderedPages: {
          basePath: "/assets/works/kitchen-processing-platform/pages",
          extension: "png",
          version: "20260803-1",
          width: 1662,
          height: 6766,
        },
        outcome: {
          heading: "运营稿发布后的内容表现",
          summary: "这份运营稿上线后进入厂内知识库排行；PV / UV 变化将在补充横向数据图后，继续沿用同一结果区呈现。",
          ranking: {
            label: "厂内内容排行",
            image: "/assets/works/kitchen-processing-platform/ranking.jpg",
            width: 1820,
            height: 852,
            alt: "无暇不出加工台运营稿在厂内知识库排行与知识达人周榜中的截图",
            caption: "内容榜单中“无暇不出，仅展示加工台「PPT/信息图」效果全面升级”位列 TOP1；截图下方同时保留作者知识达人周榜信息。",
          },
          metrics: {
            label: "PV / UV 数据变化",
            heading: "PPT / 信息图任务发起",
            summary: "以两个完整周对照运营稿发布前后的任务发起表现；当前周（08.03–08.09）尚未完整，不纳入增长计算。",
            beforeLabel: "发布前完整周 · 07.20–07.26",
            afterLabel: "发布后完整周 · 07.27–08.02",
            source: "来源：AI知识加工台_1785925809729.xlsx · 任务发起次数分布-周维度；PPT演示文稿与信息图合计。",
            scaleMax: 1600,
            rows: [
              { label: "PV", description: "任务发起次数", before: 575, after: 1422, change: "+147%" },
              { label: "UV", description: "去重用户数", before: 167, after: 424, change: "+154%" },
            ],
            dataDocumentId: "kitchen-processing-platform-data",
          },
        },
      },
      {
        id: "kitchen-processing-platform-data",
        title: "AI 知识加工台具体数据",
        format: "XLSX",
        contentType: "workbook",
        file: "/assets/works/kitchen-processing-platform/data/AI知识加工台.xlsx",
        sheets: [
          { id: "core-week", label: "核心报表 · 周", name: "核心报表-周维度", image: "/assets/works/kitchen-processing-platform/workbook-pages/core-week.png", width: 4434, height: 386 },
          { id: "core-day", label: "核心报表 · 日", name: "核心报表-日维度", image: "/assets/works/kitchen-processing-platform/workbook-pages/core-day.png", width: 14141, height: 654 },
          { id: "task-total-pv", label: "任务累计 PV", name: "任务发起次数分布-累计-pv", image: "/assets/works/kitchen-processing-platform/workbook-pages/task-total-pv.png", width: 303, height: 669 },
          { id: "task-day-pv", label: "任务当日 PV", name: "任务发起次数分布-日维度-pv", image: "/assets/works/kitchen-processing-platform/workbook-pages/task-day-pv.png", width: 303, height: 569 },
          { id: "task-week", label: "任务分布 · 周", name: "任务发起次数分布-周维度", image: "/assets/works/kitchen-processing-platform/workbook-pages/task-week.png", width: 4421, height: 1326 },
          { id: "task-day", label: "任务分布 · 日", name: "任务发起次数分布-日维度", image: "/assets/works/kitchen-processing-platform/workbook-pages/task-day.png", width: 14100, height: 2535 },
          { id: "retention", label: "用户留存", name: "用户留存", image: "/assets/works/kitchen-processing-platform/workbook-pages/retention.png", width: 9956, height: 218 },
        ],
      },
    ],
    objectHotspots: [
      {
        id: "kitchen-book",
        number: "01",
        label: "心相印营销策划",
        directoryImage: "/assets/rooms/objects/kitchen-book.png",
        documentIds: ["heartprint-marketing", "heartprint-introduction"],
        path: "M 1078.8 1292.0 1027.6 1299.3 1008.9 1312.9 987.9 1313.4 957.0 1327.4 943.2 1327.9 946.4 1332.8 922.5 1341.5 912.0 1351.7 949.2 1408.5 978.9 1445.9 1164.9 1372.1 1091.5 1295.9 1080.4 1292.0 Z",
        glowImage: {
          file: "/assets/rooms/objects/kitchen-book.png",
          x: 909.81,
          y: 1289.82,
          width: 257.38,
          height: 158.37,
        },
      },
      {
        id: "kitchen-pot",
        number: "02",
        label: "无暇不出——加工台运营稿",
        directoryImage: "/assets/rooms/objects/kitchen-pot-directory.png",
        documentId: "kitchen-processing-platform",
        path: "M555 969 C586 968 611 977 618 986 C627 983 638 987 640 995 C642 1002 635 1009 624 1013 C622 1024 622 1042 619 1050 C614 1064 590 1071 559 1072 C528 1072 504 1063 499 1049 C497 1044 499 1040 498 1037 C489 1040 477 1037 473 1030 C469 1023 475 1016 483 1012 C490 1008 497 1010 501 1015 C501 1008 496 1002 496 994 C497 982 522 970 555 969 Z",
        glowImage: {
          file: "/assets/rooms/objects/kitchen-pot-aligned.png",
          x: 0,
          y: 0,
          width: 2048,
          height: 2048,
        },
      },
      {
        id: "kitchen-radio",
        number: "03",
        label: "泡泡玛特「酷导演的剧本 —— 泡泡梦工厂」整合营销策划",
        directoryImage: "/assets/rooms/objects/kitchen-radio.png",
        documentIds: ["popmart-marketing", "popmart-introduction"],
        path: "M1692 985 L1754 1047 M1644 1030 L1668 1016 L1762 1038 L1789 1061 L1788 1129 L1764 1154 L1663 1127 L1640 1105 L1640 1053 Z",
        glowImage: {
          file: "/assets/rooms/objects/kitchen-radio.png",
          x: 1580,
          y: 970,
          width: 265,
          height: 200,
        },
      },
      {
        id: "kitchen-plant",
        number: "04",
        label: "可远观不可亵玩",
        directoryImage: "/assets/rooms/objects/kitchen-plant.png",
        documentId: "kitchen-distant-view",
        path: "M320 1058 C351 1055 374 1080 365 1110 C399 1093 432 1107 429 1132 C425 1152 388 1162 355 1150 C389 1165 414 1185 405 1205 C395 1223 363 1218 342 1208 L333 1278 C360 1271 382 1288 372 1306 C360 1324 335 1312 322 1326 L366 1328 L396 1351 L384 1408 L349 1428 L258 1428 L230 1405 L228 1354 L251 1328 L287 1320 L285 1208 C251 1214 220 1197 227 1177 C234 1157 270 1160 291 1169 C260 1146 244 1118 260 1101 C276 1085 298 1101 310 1114 C297 1086 299 1066 320 1058 Z",
        glowImage: {
          file: "/assets/rooms/objects/kitchen-plant.png",
          x: 185,
          y: 1048,
          width: 290,
          height: 390,
        },
      },
    ],
    hotspotPath: "M744 498 L946 615 L946 790 L744 907 L540 790 L540 617 Z",
    hotspotCenter: { x: 744, y: 700 },
    transition: {
      sourceFinal: { x: 0.2, y: -3.4, scale: 1.16, blur: 5 },
      detailInitial: { x: 0.5, y: 12.5, scale: 0.56, blur: 6 },
    },
  },
  {
    id: "living",
    number: "03",
    title: "Living Room",
    path: "/rooms/living",
    image: "/assets/rooms/living-cutout.png",
    directoryImage: "/assets/rooms/home-directory-sofa.png",
    alt: "Isometric living room with green sofa, media console, and a round coffee table",
    description: "A category for selected visual narratives and interactive work.",
    projects: [
      { id: "project-01", title: "Project placeholder 01", type: "Interactive design", year: "2026" },
      { id: "project-02", title: "Project placeholder 02", type: "Visual narrative", year: "2025" },
    ],
    documents: [
      {
        id: "living-personal-work-knowledge-management",
        title: "个人工作知识管理",
        format: "PDF",
        pages: 1,
        renderedPages: {
          basePath: "/assets/works/living-personal-work-knowledge-management/pages",
          extension: "jpg",
          version: "20260822-2",
          width: 1652,
          height: 5578,
        },
        setupPlan: {
          title: "快速搭建方案",
          file: "/assets/works/living-personal-work-knowledge-management/setup-plan.txt?v=2",
        },
      },
      {
        id: "living-project-space-introduction",
        title: "【一期】组织档案沉淀 V2.0",
        format: "PDF",
        pages: 1,
        workIntro: {
          kicker: "PRODUCT DESIGN · INTERACTIVE PROTOTYPE",
          summary: "项目空间将分散在群聊、知识库、会议、iCafe、代码库和链接附件中的协作信息，聚合为可检索、可追溯的项目知识。",
          coverImage: "/assets/works/living-project-space-introduction/cover.jpg",
          coverAlt: "项目空间 Demo 的项目列表界面",
          coverWidth: 1280,
          coverHeight: 720,
          action: {
            label: "查看作品",
            ariaLabel: "查看作品：项目空间 Demo",
            targetDocumentId: "living-project-space-demo",
          },
        },
        renderedPages: {
          basePath: "/assets/works/living-project-space-introduction/pages",
          extension: "png",
          version: "20260801-1",
          width: 1466,
          height: 10754,
        },
      },
      {
        id: "living-project-space-demo",
        title: "项目空间 Demo",
        format: "Interactive HTML",
        contentType: "embed",
        embedUrl: "/assets/works/living-project-space-demo/",
      },
    ],
    objectHotspots: [
      {
        id: "living-book",
        number: "02",
        label: "个人工作知识管理",
        directoryImage: "/assets/rooms/objects/living-book.png",
        ariaLabel: "打开个人工作知识管理",
        documentId: "living-personal-work-knowledge-management",
        path: "M 1098 1177 L 1211 1242 L 1209 1262 L 1071 1338 L 959 1277 L 958 1257 Z",
        glowMask: {
          file: "/assets/rooms/objects/living-book-mask.png?v=1",
        },
      },
      {
        id: "living-tv",
        number: "01",
        label: "【一期】组织档案沉淀 V2.0",
        directoryImage: "/assets/rooms/objects/living-tv.png",
        documentId: "living-project-space-introduction",
        path: "M 1398 784 L 1410 777 L 1745 977 L 1745 1226 L 1732 1243 L 1398 1045 Z M 1463 1127 L 1492 1121 L 1621 1215 L 1629 1237 L 1619 1244 L 1605 1243 L 1570 1218 L 1463 1141 Z",
        glowImage: {
          file: "/assets/rooms/objects/living-tv.png",
          x: 1390,
          y: 768,
          width: 361,
          height: 478,
        },
      },
    ],
    hotspotPath: "M980 327 L1175 451 L1175 616 L946 711 L946 614 L744 498 L802 456 L871 396 Z",
    hotspotCenter: { x: 970, y: 515 },
    transition: {
      sourceFinal: { x: -3.2, y: 0.5, scale: 1.16, blur: 6 },
      detailInitial: { x: 22.5, y: -3.5, scale: 0.58, blur: 7 },
    },
  },
  {
    id: "study",
    number: "04",
    title: "Study",
    path: "/rooms/study",
    image: "/assets/rooms/study-cutout.png",
    directoryImage: "/assets/rooms/home-directory-book.png?v=2",
    alt: "Isometric study with dark timber bookshelves, floral seating, and an easel",
    description: "A category for research-led, editorial, and reflective projects.",
    projects: [
      { id: "project-01", title: "Project placeholder 01", type: "Editorial design", year: "2026" },
      { id: "project-02", title: "Project placeholder 02", type: "Research project", year: "2025" },
    ],
    documents: [
      {
        id: "model-experience-4",
        title: "模型体验台细节优化 4.0",
        format: "PDF",
        pages: 1,
        file: "/assets/works/study-model-experience/model-experience-4.0.pdf",
        preface: {
          video: "/assets/works/study-model-experience/model-experience-overview.mp4?v=2",
          titleSplitY: 116,
          paragraphs: [
            "模型体验台是一款承载多模型对话、模型对比、图片生成、视频生成及附件输入等能力的一站式 AI 模型体验产品。随着产品从基础能力建设进入规模化使用阶段，用户关注点逐渐从“模型能否生成结果”，转向“任务过程是否清晰、等待是否可控、内容是否易于管理、结果是否方便复用”。",
            "本轮迭代基于真实用户反馈，围绕上传状态、视频生成反馈、跨会话完成通知、长对话定位、历史会话管理、生图参数简化和对话分享等场景，完成了 10 项体验需求的梳理与方案设计。我主要负责用户问题归因、需求优先级判断、核心流程设计、推进验收等工作，将零散反馈转化为可开发、可验收的产品方案。",
            "当前，对比模式、Markdown 展示、长对话定位、生图默认参数及模型名称展示等能力已上线，其余需求正在按优先级持续推进。以下为本轮迭代的完整 PRD。",
          ],
        },
        renderedPages: {
          basePath: "/assets/works/study-model-experience/pages",
          extension: "jpg",
          width: 1190,
          height: 15274,
        },
      },
      {
        id: "model-experience-usage-analysis",
        title: "模型体验台使用情况分析报告",
        format: "PDF",
        pages: 25,
        transparentPages: true,
        renderedPages: {
          basePath: "/assets/works/study-model-usage-analysis/transparent-pages",
          extension: "webp",
          version: "20260731-4",
          width: 1190,
          height: 1684,
          pageHeights: [1285, 1166, 1532, 1103, 1444, 1489, 1247, 1568, 1676, 1553, 953, 1649, 1212, 1435, 1535, 1505, 1525, 908, 1535, 1408, 1507, 1248, 1270, 1506, 1833],
        },
        links: [
          {
            id: "interview-materials",
            page: 1,
            label: "访谈材料：",
            ariaLabel: "打开访谈分析报告",
            targetDocumentId: "study-interview-analysis",
            x: 86,
            y: 328,
            width: 104,
            height: 49,
          },
          {
            id: "navigation-how",
            page: 1,
            label: "怎么用",
            displayLabel: "「怎么用」",
            ariaLabel: "跳转到怎么用，第 5 页",
            targetPage: 5,
            repaintLabel: true,
            surface: "tinted",
            x: 104,
            y: 492,
            width: 92,
            height: 26,
            cover: {
              x: 536,
              y: 484,
              width: 122,
              height: 42,
            },
          },
          {
            id: "navigation-what",
            page: 1,
            label: "做什么",
            displayLabel: "「做什么」",
            ariaLabel: "跳转到做什么，第 7 页",
            targetPage: 7,
            repaintLabel: true,
            x: 104,
            y: 542,
            width: 90,
            height: 26,
          },
          {
            id: "navigation-why",
            page: 1,
            label: "为什么选",
            displayLabel: "「为什么选」",
            ariaLabel: "跳转到为什么选，第 10 页",
            targetPage: 10,
            repaintLabel: true,
            x: 104,
            y: 591,
            width: 108,
            height: 26,
          },
          {
            id: "navigation-who",
            page: 1,
            label: "是什么人",
            displayLabel: "「是什么人」",
            ariaLabel: "跳转到是什么人，第 12 页",
            targetPage: 12,
            repaintLabel: true,
            x: 104,
            y: 641,
            width: 108,
            height: 26,
          },
          {
            id: "navigation-opportunity",
            page: 1,
            label: "新机会",
            displayLabel: "「新机会」",
            ariaLabel: "跳转到新机会，第 14 页",
            targetPage: 14,
            repaintLabel: true,
            x: 104,
            y: 690,
            width: 90,
            height: 26,
          },
        ],
      },
      {
        id: "study-interview-analysis",
        title: "访谈分析报告",
        format: "PDF",
        pages: 8,
        transparentPages: true,
        renderedPages: {
          basePath: "/assets/works/study-interview-analysis/transparent-pages",
          extension: "webp",
          version: "20260731-1",
          width: 1190,
          height: 1684,
          pageHeights: [1488, 1546, 1001, 1558, 1539, 1528, 1559, 957],
        },
      },
      {
        id: "study-enterprise-ai-search",
        title: "企业 AI 搜索升级为数字员工",
        format: "PDF",
        pages: 1,
        file: "/assets/works/study-enterprise-ai-search/enterprise-ai-search-prd.pdf",
        introduction: {
          kicker: "PRODUCT CASE / 企业级 AI 搜索",
          heading: "企业 AI 搜索升级为数字员工",
          meta: [
            { label: "项目类型", value: "企业级 AI 搜索升级 / 数字员工产品设计" },
            { label: "我的角色", value: "产品经理" },
            { label: "负责内容", value: "问题分析、产品定位、需求拆解、搜索入口设计、核心问答链路及数据埋点设计" },
            { label: "当前阶段", value: "主要方案已完成并进入分阶段交付，核心埋点已验收" },
          ],
          sections: [
            {
              heading: "项目背景",
              paragraphs: [
                "企业 AI 搜索是面向公司内部知识查询场景的智能问答产品。用户可以通过自然语言查询企业制度、业务资料和项目知识，并在已有答案的基础上继续追问、总结内容或查看参考来源。",
                "在用户反馈和产品体验自查中，我发现原有方案存在两个主要问题：一方面，通用 Agent 需要经过多轮推理和工具调用，响应时间较长，调用链路也存在一定的稳定性风险；另一方面，AI 问答依附在传统搜索入口中，触发方式不够明确，用户难以建立“企业问题可以直接问 AI”的使用认知。",
              ],
            },
            {
              heading: "项目目标",
              paragraphs: [
                "本次迭代的重点，是将原有的企业搜索能力从“超级助理”中独立出来，升级为定位更清晰的“企业 AI 搜索”数字员工。产品不再同时承接差旅、休假等多个场景，而是聚焦企业知识查询、连续追问、内容总结和参考资料定位。通过收缩能力范围，减少不必要的工具调用，使产品更符合高频搜索场景对响应速度、稳定性和答案可信度的要求。",
              ],
            },
            {
              heading: "我的工作",
              paragraphs: [
                "在项目中，我主要负责梳理原有产品的问题，协助重新定义企业 AI 搜索的产品定位和能力边界。",
                "围绕“用户如何找到产品、如何完成提问、如何继续使用”的完整路径，设计如流搜索、内搜等场景中的“问 AI”入口。用户已经输入搜索内容时，可以携带当前问题进入企业 AI 搜索并直接生成答案，减少从传统搜索切换到 AI 问答的操作成本。",
                "在数字员工内部，进一步完善推荐提问、历史会话、连续追问、互联网搜索开关、参考资源和模型选择等能力，并简化对普通用户帮助有限的工具调用过程。针对不同模型的能力和成本差异，模型列表中增加了能力描述、内部标签和价格倍率，帮助用户根据实际任务选择模型。",
              ],
            },
            {
              heading: "项目进展",
              paragraphs: [
                "目前，产品定位、搜索入口、数字员工问答链路、模型选择及数据埋点等主要方案已经完成，项目进入分阶段交付阶段，核心埋点已验收。后续将结合入口点击、问题提交和答案反馈等数据，持续验证用户从传统搜索转向 AI 搜索的实际效果。",
              ],
            },
          ],
          source: {
            kicker: "02 / PRODUCT REQUIREMENTS",
            heading: "完整 PRD",
          },
        },
        renderedPages: {
          basePath: "/assets/works/study-enterprise-ai-search/pages",
          extension: "png",
          version: "20260810-1",
          width: 1190,
          height: 8929,
          pageHeights: [8929],
        },
      },
      {
        id: "study-intelligent-knowledge-assistant",
        title: "智能知识助手升级一期",
        format: "PDF",
        pages: 1,
        file: "/assets/works/study-intelligent-knowledge-assistant/intelligent-knowledge-assistant-prd.pdf",
        introduction: {
          kicker: "PRODUCT CASE / 企业知识订阅",
          heading: "智能知识助手升级一期",
          sections: [
            {
              heading: "项目概述",
              paragraphs: [
                "智能知识助手是一款面向企业员工的知识订阅与问答产品，用户可以通过自然语言设置关注主题和推送时间，由系统定期检索、筛选并整理相关内容，实现从主动搜索到持续获取信息的转变。",
                "本轮升级建立在内部真实订阅需求的基础上。战略、法务、研发、市场等不同团队都存在持续获取行业资讯和业务情报的需求，但个人用户不希望配置复杂规则，团队用户又需要更精细的主题、信源和推送策略。针对这一问题，我将产品方案拆分为个人端和团队端两条路径：个人用户通过预设主题和自然语言快速完成订阅，团队用户则可以围绕业务方向配置专属资讯服务。",
                "在项目中，我主要负责需求分析、用户分层、产品目标制定和核心链路设计，完成了首次订阅引导、自然语言创建与管理订阅、定时推送、工作卡展示及知识库沉淀等方案，并规划了侧边栏配置和群聊订阅等后续能力。目前，一期核心方案已完成需求设计，团队配置与群聊协作能力纳入二期规划。以下为本次升级的完整 PRD。",
              ],
            },
          ],
          source: {
            kicker: "02 / PRODUCT REQUIREMENTS",
            heading: "完整 PRD",
          },
        },
        renderedPages: {
          basePath: "/assets/works/study-intelligent-knowledge-assistant/pages",
          extension: "png",
          version: "20260811-3",
          width: 1190,
          height: 9754,
          pageHeights: [9754],
        },
      },
    ],
    objectHotspots: [
      {
        id: "study-book",
        number: "01",
        label: "模型体验台细节优化 4.0",
        directoryImage: "/assets/rooms/objects/study-book.png",
        documentId: "model-experience-4",
        path: "M941 1255 L964 1228 L987 1202 L1010 1175 L1033 1162 L1056 1167 L1079 1169 L1103 1171 L1126 1179 L1149 1189 L1172 1190 L1195 1200 L1218 1211 L1241 1219 L1264 1239 L1241 1266 L1218 1294 L1195 1322 L1172 1320 L1149 1313 L1126 1307 L1103 1300 L1079 1293 L1056 1289 L1033 1281 L1010 1274 L987 1268 L964 1263 L941 1256 Z",
        glowImage: {
          file: "/assets/rooms/objects/study-book.png",
          x: 940,
          y: 1160,
          width: 325.45,
          height: 167.44,
        },
      },
      {
        id: "study-lamp",
        number: "02",
        label: "模型体验台使用情况分析报告",
        directoryImage: "/assets/rooms/objects/study-lamp.png",
        documentId: "model-experience-usage-analysis",
        path: "M1060 589 C1060 575 1072 573 1088 573 C1105 573 1116 578 1116 590 C1116 602 1107 608 1089 610 C1072 608 1061 601 1060 589 Z M1086 608 L1090 608 L1090 753 L1086 753 Z M1088 754 C1110 754 1135 761 1147 774 L1179 867 C1183 885 1170 899 1148 908 C1129 916 1107 920 1087 921 C1064 920 1040 916 1017 908 C997 900 990 885 995 868 L1027 773 C1042 761 1065 754 1088 754 Z",
        glowImage: {
          file: "/assets/rooms/objects/study-lamp.png",
          x: 992.5,
          y: 572.7,
          width: 190,
          height: 349.6,
        },
      },
      {
        id: "study-board",
        number: "03",
        label: "企业 AI 搜索升级为数字员工",
        directoryImage: "/assets/rooms/objects/study-board-directory.png",
        documentId: "study-enterprise-ai-search",
        path: "M 466 1050 L 686 972 L 749 1397 L 536 1518 Z",
        glowImage: {
          file: "/assets/rooms/objects/study-board-aligned.png",
          x: 0,
          y: 0,
          width: 2048,
          height: 2048,
        },
      },
      {
        id: "study-sofa",
        number: "04",
        label: "智能知识助手升级一期",
        directoryImage: "/assets/rooms/objects/study-sofa.png",
        documentId: "study-intelligent-knowledge-assistant",
        path: "M 884 1454 C 926 1437 979 1451 1010 1475 L 1087 1462 C 1137 1468 1176 1510 1183 1574 L 1175 1688 L 1135 1760 L 1068 1774 L 971 1760 L 888 1735 L 852 1686 L 845 1570 L 858 1496 Z",
        glowImage: {
          file: "/assets/rooms/objects/study-sofa.png",
          x: 845,
          y: 1445,
          width: 340,
          height: 325,
        },
      },
    ],
    hotspotPath: "M744 151 L980 327 L871 396 L802 456 L744 490 L499 382 L499 322 Z",
    hotspotCenter: { x: 744, y: 330 },
    transition: {
      sourceFinal: { x: 0.5, y: 3.4, scale: 1.18, blur: 5 },
      detailInitial: { x: 0, y: -24, scale: 0.54, blur: 6 },
    },
  },
  {
    id: "doorstep",
    number: "05",
    title: "Doorstep",
    path: "/rooms/doorstep",
    image: "/assets/rooms/doorstep-house-final.webp?v=1",
    directoryImage: "/assets/rooms/home-directory-doorstep.png?v=2",
    alt: "暖色等距视角门廊小屋，包含开放木门、鞋柜、联系图标、小狗和地垫",
    description: "A quiet goodbye at the doorstep.",
    isDoorstep: true,
    projects: [],
    documents: [],
    objectHotspots: [
      {
        id: "doorstep-wechat",
        number: "01",
        label: "微信号",
        ariaLabel: "复制微信号",
        path: "M 776 169 C 772 168 767 170 763 173 L 759 178 C 756 182 756 187 756 194 L 756 270 C 756 278 760 284 767 289 L 854 336 C 861 340 866 335 867 329 C 868 326 867 321 867 317 L 867 227 C 867 220 864 214 859 211 L 786 170 C 783 168 779 168 776 169 Z",
        glowMask: {
          file: "/assets/rooms/objects/doorstep-wechat-mask.png?v=1",
        },
        action: {
          type: "copy",
          value: "ledwechat15945158337",
          successMessage: "已复制微信号",
        },
        excludeFromProgress: true,
      },
      {
        id: "doorstep-email",
        number: "02",
        label: "163 邮箱",
        ariaLabel: "复制邮箱地址",
        path: "M 888 245 L 959 268 C 970 271 977 280 977 291 L 977 344 C 977 355 969 363 959 360 L 886 331 C 875 327 869 318 869 308 L 869 263 C 869 252 877 244 888 245 Z",
        glowMask: {
          file: "/assets/rooms/objects/doorstep-email-mask.png?v=1",
        },
        action: {
          type: "copy",
          value: "15945158337@163.com",
          successMessage: "已复制邮箱",
        },
        excludeFromProgress: true,
      },
      {
        id: "doorstep-resume",
        number: "03",
        label: "个人简历",
        ariaLabel: "下载个人简历",
        path: "M 1013 309 L 1082 331 C 1092 334 1098 344 1098 355 L 1098 438 C 1098 450 1089 457 1078 454 L 1008 431 C 998 427 992 418 992 407 L 992 327 C 992 315 1001 307 1013 309 Z",
        glowMask: {
          file: "/assets/rooms/objects/doorstep-resume-mask.png?v=1",
        },
        action: {
          type: "download",
          file: "/assets/works/doorstep-resume.pdf?v=1",
          filename: "杨昕乔简历.pdf",
          successMessage: "简历下载",
        },
        excludeFromProgress: true,
      },
      {
        id: "doorstep-bilibili",
        number: "04",
        label: "Bilibili",
        ariaLabel: "打开 Bilibili 主页",
        path: "M 817 350 L 891 376 C 900 379 906 388 906 399 L 906 476 C 906 486 897 493 888 490 L 812 463 C 803 460 798 451 798 441 L 798 369 C 798 358 807 350 817 350 Z",
        glowMask: {
          file: "/assets/rooms/objects/doorstep-bilibili-mask.png?v=1",
        },
        action: {
          type: "link",
          url: "https://space.bilibili.com/702930217?spm_id_from=333.1007.0.0",
        },
        excludeFromProgress: true,
      },
      {
        id: "doorstep-github",
        number: "05",
        label: "GitHub",
        ariaLabel: "打开 GitHub 主页",
        path: "M 930 423 L 1036 454 C 1047 457 1054 467 1054 478 L 1054 548 C 1054 559 1046 567 1035 564 L 929 533 C 918 530 911 521 911 510 L 911 445 C 911 434 919 423 930 423 Z",
        glowMask: {
          file: "/assets/rooms/objects/doorstep-github-mask.png?v=1",
        },
        action: {
          type: "link",
          url: "https://github.com/jojoyangupupup/",
        },
        excludeFromProgress: true,
      },
    ],
    hotspotPath: "M 0 0 Z",
    hotspotCenter: { x: 0, y: 0 },
    transition: {
      sourceFinal: { x: 0.5, y: 0.5, scale: 1, blur: 0 },
      detailInitial: { x: 0.5, y: 0.5, scale: 1, blur: 0 },
    },
  },
];

// Top tabs and Previous/Next arrows share this single cyclic page order.
export const PAGE_NAVIGATION = [
  { id: "overview", label: "首页", accessibleLabel: "Overview", path: "/", type: "overview" },
  { id: "living", label: "客厅", accessibleLabel: "Living Room", path: "/rooms/living", type: "room", roomId: "living" },
  { id: "study", label: "书房", accessibleLabel: "Study", path: "/rooms/study", type: "room", roomId: "study" },
  { id: "kitchen", label: "厨房", accessibleLabel: "Kitchen", path: "/rooms/kitchen", type: "room", roomId: "kitchen" },
  { id: "garden", label: "花园", accessibleLabel: "Garden", path: "/rooms/garden", type: "room", roomId: "garden" },
  { id: "doorstep", label: "门廊", accessibleLabel: "Doorstep", path: "/rooms/doorstep", type: "room", roomId: "doorstep" },
];

export function roomFromPath(pathname) {
  const normalized = pathname.replace(/\/+$/, "") || "/";
  return ROOMS.find((room) => room.path === normalized) || null;
}

export function adjacentPages(pageId) {
  const index = PAGE_NAVIGATION.findIndex((item) => item.id === pageId);
  return {
    previous: PAGE_NAVIGATION[(index - 1 + PAGE_NAVIGATION.length) % PAGE_NAVIGATION.length],
    next: PAGE_NAVIGATION[(index + 1) % PAGE_NAVIGATION.length],
  };
}
